/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppdb.siswa;

public class OutputFrame extends javax.swing.JFrame {
    
    private Biodata bio;
    private Ortu ortu;
    private Nilai nilai;
    private Output output ;
   
    public OutputFrame() {
        initComponents();
    }
    
    public void setOutput() {
    // ----------BIODATA-----------------
        txtNISN.setText(bio.getNisn());
        txtNama.setText(bio.getNama());
        String ttl = bio.getTmptLahir() +", "+ bio.getTglLahir();
        txtTTL.setText(ttl);
        txtKelamin.setText(bio.getKelamin());
        txtAgama.setText(bio.getAgama());
        txtTelp.setText(bio.getTelp());
        txtAlamat.setText(bio.getAlamat());
        
    //----------ORTU-------------------
        namaAyah.setText(ortu.getNamaAyah());
        pekerjaanAyah.setText(ortu.getPekerjaanAyah());
        gajiAyah.setText(ortu.getGajiAyah());
        telpAyah.setText(ortu.getTelpAyah());
        alamatAyah.setText(ortu.getAlamatAyah());
        
        namaIbu.setText(ortu.getNamaIbu());
        pekerjaanIbu.setText(ortu.getPekerjaanIbu());
        gajiIbu.setText(ortu.getGajiIbu());
        telpIbu.setText(ortu.getTelpIbu());
        alamatIbu.setText(ortu.getAlamatIbu());
    
    
    
    //----------NILAI------------------
        nilaiMTK.setText("Matematika : "+ Float.toString(nilai.getMtk()));
        nilaiBIND.setText("Bahasa Indonesia : "+ Float.toString(nilai.getBindo()));
        nilaiBING.setText("Bahasa Inggris : "+ Float.toString(nilai.getBing()));
        nilaiIPA.setText("IPA : "+ Float.toString(nilai.getIpa()));
        nilaiRATATA.setText("Nilai Rata Rata : "+ Float.toString(nilai.getRataRata()));
    }

    public void setBio(Biodata bio) {
        this.bio = bio;
    }

    public void setOrtu(Ortu ortu) {
        this.ortu = ortu;
    }
    
    public void setNilai(Nilai nilai) {
        this.nilai = nilai;
    }
    
    public void setOutput(Output output) {
        this.output = output ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNISN = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtTTL = new javax.swing.JLabel();
        txtKelamin = new javax.swing.JLabel();
        txtAgama = new javax.swing.JLabel();
        txtTelp = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        namaAyah = new javax.swing.JLabel();
        pekerjaanAyah = new javax.swing.JLabel();
        gajiAyah = new javax.swing.JLabel();
        telpAyah = new javax.swing.JLabel();
        alamatAyah = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        namaIbu = new javax.swing.JLabel();
        pekerjaanIbu = new javax.swing.JLabel();
        gajiIbu = new javax.swing.JLabel();
        telpIbu = new javax.swing.JLabel();
        alamatIbu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nilaiMTK = new javax.swing.JLabel();
        nilaiBIND = new javax.swing.JLabel();
        nilaiBING = new javax.swing.JLabel();
        nilaiIPA = new javax.swing.JLabel();
        nilaiRATATA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMASI PENDAFTAR");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biodata Siswa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtNISN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNISN.setText("jLabel1");

        txtNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNama.setText("jLabel1");

        txtTTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTTL.setText("jLabel1");

        txtKelamin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKelamin.setText("jLabel1");

        txtAgama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAgama.setText("jLabel1");

        txtTelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTelp.setText("jLabel1");

        txtAlamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlamat.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNISN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtTTL, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtKelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtAgama, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNISN)
                .addGap(18, 18, 18)
                .addComponent(txtNama)
                .addGap(18, 18, 18)
                .addComponent(txtTTL)
                .addGap(18, 18, 18)
                .addComponent(txtKelamin)
                .addGap(18, 18, 18)
                .addComponent(txtAgama)
                .addGap(18, 18, 18)
                .addComponent(txtTelp)
                .addGap(18, 18, 18)
                .addComponent(txtAlamat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biodata Siswa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayah"));

        namaAyah.setText("jLabel1");

        pekerjaanAyah.setText("jLabel1");

        gajiAyah.setText("jLabel1");

        telpAyah.setText("jLabel1");

        alamatAyah.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pekerjaanAyah)
                    .addComponent(gajiAyah)
                    .addComponent(telpAyah)
                    .addComponent(alamatAyah)
                    .addComponent(namaAyah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaAyah)
                .addGap(18, 18, 18)
                .addComponent(pekerjaanAyah)
                .addGap(18, 18, 18)
                .addComponent(gajiAyah)
                .addGap(18, 18, 18)
                .addComponent(telpAyah)
                .addGap(18, 18, 18)
                .addComponent(alamatAyah)
                .addGap(24, 24, 24))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ibu"));

        namaIbu.setText("jLabel1");

        pekerjaanIbu.setText("jLabel1");

        gajiIbu.setText("jLabel1");

        telpIbu.setText("jLabel1");

        alamatIbu.setText("jLabel1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatIbu)
                    .addComponent(telpIbu)
                    .addComponent(gajiIbu)
                    .addComponent(pekerjaanIbu)
                    .addComponent(namaIbu))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaIbu)
                .addGap(18, 18, 18)
                .addComponent(pekerjaanIbu)
                .addGap(18, 18, 18)
                .addComponent(gajiIbu)
                .addGap(18, 18, 18)
                .addComponent(telpIbu)
                .addGap(18, 18, 18)
                .addComponent(alamatIbu)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nilai Siswa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        nilaiMTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nilaiMTK.setText("Matematika");

        nilaiBIND.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nilaiBIND.setText("Bahasa Indo");

        nilaiBING.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nilaiBING.setText("Bahasa Inggris");

        nilaiIPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nilaiIPA.setText("IPA");

        nilaiRATATA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nilaiRATATA.setText("rata rata");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nilaiMTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilaiBIND, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(nilaiBING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(nilaiIPA, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(nilaiRATATA, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nilaiMTK)
                .addGap(18, 18, 18)
                .addComponent(nilaiBIND)
                .addGap(18, 18, 18)
                .addComponent(nilaiBING)
                .addGap(18, 18, 18)
                .addComponent(nilaiIPA)
                .addGap(18, 18, 18)
                .addComponent(nilaiRATATA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatAyah;
    private javax.swing.JLabel alamatIbu;
    private javax.swing.JLabel gajiAyah;
    private javax.swing.JLabel gajiIbu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel namaAyah;
    private javax.swing.JLabel namaIbu;
    private javax.swing.JLabel nilaiBIND;
    private javax.swing.JLabel nilaiBING;
    private javax.swing.JLabel nilaiIPA;
    private javax.swing.JLabel nilaiMTK;
    private javax.swing.JLabel nilaiRATATA;
    private javax.swing.JLabel pekerjaanAyah;
    private javax.swing.JLabel pekerjaanIbu;
    private javax.swing.JLabel telpAyah;
    private javax.swing.JLabel telpIbu;
    private javax.swing.JLabel txtAgama;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtKelamin;
    private javax.swing.JLabel txtNISN;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtTTL;
    private javax.swing.JLabel txtTelp;
    // End of variables declaration//GEN-END:variables
}
